#!/bin/bash
ac=`acpi -a | awk '{print $3}' | tr -d ,`
percent1=`acpi -b | acpi -b | awk '{print $4}' | cut -d % -f 1 | sed -n 1p`
percent2=`acpi -b | acpi -b | awk '{print $4}' | cut -d % -f 1 | sed -n 2p`
avgPercent=$(((percent1+percent2)/2))

prettyPrintPercent(){
    if [ $1 -lt 20 ]
    then
        icon="";
    elif [ $1 -lt 40 ]
    then
        icon="";
    elif [ $1 -lt 60 ]
    then
        icon="";
    elif [ $1 -lt 80 ]
    then
        icon="";
    else
        icon=""
    fi
    eval "$2+='$icon $1%'";
}

percentColor(){
    if [ $1 -lt 20 ]
    then
        # red
        color="#dc322f"
    elif [ $1 -lt 40 ]
    then
        # orange
        color="#cb4b16"
    elif [ $1 -lt 60 ]
    then
        # yellow
        color="#b58900"
    elif [ $1 -lt 80 ]
    then
        # cyan
        color="#2aa198"
    elif [ $1 -lt 101 ]
    then
        # blue
        color="#268bd2"
    # >= 101 - charging
    else
        # green
        color="#859900"
    fi

    eval "$2='$color'";
}

fullLabel=""
prettyPrintPercent $percent1 fullLabel
fullLabel+=" "
prettyPrintPercent $percent2 fullLabel

avgLabel=""
prettyPrintPercent $avgPercent avgLabel

labelColor=""
statusLabel=""

if [ $ac == "on-line" ]
then
    statusLabel=""
    percentColor 101 avgLabelColor
else
    statusLabel=""
    percentColor $avgPercent avgLabelColor
fi

case $BLOCK_BUTTON in
    1) echo "$statusLabel  $avgLabel"; echo ""; echo "$avgLabelColor";;
    *) echo "$statusLabel  $fullLabel"; echo ""; echo "$avgLabelColor";;
esac
