#!/usr/bin/env bash

################################
# Shows current brightness
#
# dependencies:
# - brightlight @ https://github.com/multiplexd/brightlight
#
################################

case $BLOCK_BUTTON in
        # right click
        # set to 50%
        3) xbacklight -set 50 > /dev/null ;;

        # scroll up
        # raise brightness
        4) xbacklight -inc 5 > /dev/null ;;

        # scroll down
        # lower brightness
        5) xbacklight -dec 5 > /dev/null ;;
esac

brightness=`xbacklight -get | cut -d . -f 1`

echo "$brightness%"
echo "$brightness%"
echo ""
