#!/usr/bin/env bash

################################
# Shows current brightness
#
# dependencies:
# - brightnessctl @ https://github.com/Hummer12007/brightnessctl
#
################################

case $BLOCK_BUTTON in
        # right click
        # set to 50%
        3) brightnessctl s 50% > /dev/null ;;

        # scroll up
        # raise brightness
        4) brightnessctl s 5%+ > /dev/null ;;

        # scroll down
        # lower brightness
        5) brightnessctl s -5% > /dev/null ;;
esac

brightness=`brightnessctl g`

echo "$brightness%"
echo "$brightness%"
echo ""
