#!/usr/bin/env bash

################################
# Shows current brightness
#
# dependencies:
# - brightlight @ https://github.com/multiplexd/brightlight
#
################################

case $BLOCK_BUTTON in
        # right click
        # set to 50%
        3) brightlight -p -w 50 > /dev/null ;;

        # scroll up
        # raise brightness
        4) brightlight -p -i 5 > /dev/null ;;

        # scroll down
        # lower brightness
        5) brightlight -p -d 5 > /dev/null ;;
esac

brightness=`brightlight -p -r | awk '{print $5}' | cut -d % -f 1`

echo "$brightness%"
echo "$brightness%"
echo ""
