#!/bin/sh
# Copyright (C) 2015 Aaron McCall <amccall@thepacketlounge.org>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Note: Add ufw command to suderos with NOPASSWD (Do not do this on a server or non personal computer)


fwStatus=`sudo ufw status | grep -Po '(?<=Status: )(.)*'`

# Right click launch gufw
if [ "$BLOCK_BUTTON" = 3 ]; then
    sudo gufw
    exit 0
fi

# Confirm or enable ufw on left click
if [ "$fwStatus" != "active" ]; then
        echo "OFF"
        echo "OFF"
        echo "#FF0000"
        if [ "$BLOCK_BUTTON" = 1 ]; then
            sudo ufw enable > /dev/null
        else
            exit 0
        fi
fi

# Confirm or disable ufw click
if [ "$fwStatus" = "active" ]; then
    echo "ON"
    echo "ON"
    echo ""
        if [ "$BLOCK_BUTTON" = 1 ]; then
            sudo ufw disable > /dev/null
        else
            exit 0
        fi    
fi
