#!/bin/bash

if [[ -c /dev/video0 ]]; then
  # Right click - disable camera
  if [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
    sudo manage_camera off
  fi

  if [[ "$(fuser /dev/video0)" != "" ]]; then
    echo "REC"
    echo "REC"
    echo "#DC322F"
  else
    echo "ON"
    echo "ON"
    echo "#2AA198"
  fi
else
  # Right click - enable camera
  if [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
    sudo manage_camera on
  fi

   echo "OFF"
   echo "OFF"
   echo ""
fi
