#!/bin/sh

#xdotool key XF86AudioStop && \
#xkblayout-state set 0 && \
XSECURELOCK_BACKGROUND_COLOR=#002b36 XSECURELOCK_AUTH_BACKGROUND_COLOR=#002b36 XSECURELOCK_SHOW_DATETIME=1 XSECURELOCK_SHOW_HOSTNAME=0 XSECURELOCK_SHOW_USERNAME=0 xsecurelock
