[colors.normal]
black = "#073642"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"
magenta = "#6c71c4"
red = "#dc322f"
white = "#fdf6e3"
yellow = "#b58900"

[colors.primary]
background = "#002b36"
foreground = "#93a1a1"

[font]
size = 14.0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "MesloLGS NF"

[font.offset]
x = 0
y = -2

[window]
decorations = "Buttonless"
padding = { x = 0, y = 15 }

[keyboard]
bindings= [
    { key = "Back", mods = "Control", chars = "\u0017" },
    { key = "Back", mods = "Command", chars = "\u0017" },

    { key = "c", mods = "Control|Shift", action = "Copy" },
    { key = "c", mods = "Command|Shift", action = "Copy" },

    { key = "v", mods = "Control|Shift", action = "Paste" },
    { key = "v", mods = "Command|Shift", action = "Paste" },

    { key = "f", mods = "Control|Shift", action = "SearchForward" },
    { key = "f", mods = "Command|Shift", action = "SearchForward" },

    { key = "l", mods = "Command", chars= "\u000c" },

    { key = "Space", mods = "Control|Shift", action = "ToggleViMode" },
    { key = "Space", mods = "Command|Shift", action = "ToggleViMode" },

    { key = "Space", mods = "Control", action = "ToggleNormalSelection" },
    { key = "Space", mods = "Command", action = "ToggleNormalSelection" },
]
