[colors.normal]
black = "#073642"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"
magenta = "#6c71c4"
red = "#dc322f"
white = "#fdf6e3"
yellow = "#b58900"

[colors.primary]
background = "#002b36"
foreground = "#93a1a1"

[font]
size = 14.0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "MesloLGS NF"

[font.offset]
x = 0
y = -2

[keyboard]
bindings= [
    { key= "Back", mods= "Control", chars= "\u0017" },
]
