;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cua-paste
        drag-stuff-left
        drag-stuff-right
        duplicate-line
        keyboard-escape-quit
        kill-region
        markdown-exdent-or-delete
        mouse-set-region
        mwim-beginning-of-code-or-line
        mwim-end-of-code-or-line
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        cua--prefix-override-handler
        drag-stuff-down
        find-file
        js2-mode-show-node
        mark-whole-buffer
        markdown-preview
        mouse-save-then-kill
        ))
