;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        comment-dwim-2
        copy-region-as-kill
        cua--prefix-copy-handler
        cua-paste
        cua-scroll-down
        delete-window
        describe-key
        drag-stuff-left
        drag-stuff-right
        drag-stuff-up
        duplicate-current-line-or-region
        duplicate-line
        end-of-buffer
        keyboard-escape-quit
        kill-region
        kill-this-buffer
        markdown-exdent-or-delete
        mouse-set-region
        mwim-beginning-of-code-or-line
        mwim-end-of-code-or-line
        my-backward-delete-word
        my-delete-current-line
        my-delete-word
        tab-indent-or-complete
        ))

(setq mc/cmds-to-run-once
      '(
        ag-project
        ag-project-files
        beginning-of-buffer
        completion-at-point
        create-new-buffer
        cua--prefix-override-handler
        cua-copy-region
        cua-cut-region
        drag-stuff-down
        electric-pair-delete-pair
        find-file
        find-tag
        fiplr-find-file
        ignore
        js2-mode-show-node
        kmacro-end-or-call-macro
        list-buffers
        mark-whole-buffer
        markdown-preview
        mouse-drag-header-line
        mouse-save-then-kill
        mouse-select-window
        neotree-previous-line
        neotree-toggle
        new-emacs-instance
        next-error
        nxml-insert-xml-declaration
        overwrite-mode
        recentf-open-files
        smex
        tabbar-ruler-backward
        tabbar-ruler-forward
        tabbar-select-tab-callback
        undefined
        ))
